{% set name = "django-stubs" %}
{% set version = "1.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-stubs-{{ version }}.tar.gz
  sha256: 81650b08f73126130231e528b844266ae531c1f96b7663d3b31b51155be740c5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - django
    - django-stubs-ext >=0.3.0
    - mypy >=0.790
    - python >=3.6
    - toml
    - typing-extensions
    - types-pytz
    - types-pyyaml

test:
  imports:
    - django_stubs_ext
    - mypy_django_plugin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/typeddjango/django-stubs
  summary: Mypy stubs for Django
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
