{% set name = "django-stubs" %}
{% set version = "1.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-stubs-{{ version }}.tar.gz
  sha256: 11a4aa094d3da0108d268386dfd0b9a5bf73fe1ab5919b5a292607671329bc4b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - django
    - django-stubs-ext >=0.3.0
    - mypy >=0.930,<0.950
    - python >=3.7
    - tomli
    - types-pytz
    - types-pyyaml
    - typing-extensions

test:
  imports:
    - django_stubs_ext
    - mypy_django_plugin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/typeddjango/django-stubs
  summary: Mypy stubs for Django
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
